spring:
  application:
    name: AccountsService
  data:
    rest:
      base-path: /api
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
# CONFIGURE THE BELOW FOR YOUR RESPECTIVE MYSQL DB < ----------
    url: jdbc:mysql://mysql:3306/coe692data_accounts
    username: awaislocal
    password: awaislocal
    driver-class-name: com.mysql.cj.jdbc.Driver
#  ------------------ >
server:
  port: 8081
#  address: 0.0.0.0

#spring.jpa.show-sql: true
endpoints:
  TrainerServiceBaseUri: http://localhost:8083/trainer