spring:
  application:
    name: AccountsService
  data:
    rest:
      base-path: /api
      cors:
        allowed-origins: "http://localhost:3000" # Adjust the allowed origin as per your frontend host
        allowed-methods: GET, POST, PUT, DELETE, PATCH, OPTIONS
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    # Replace 'mysql' with the service name of your MySQL database in docker-compose.yml
    url: jdbc:mysql://mysql:3306/coe692data_accounts
    username: awaislocal
    password: awaislocal
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081
  # Uncomment the next line if you want the server to be accessible on all network interfaces
  # address: 0.0.0.0

# Uncomment the following line to enable SQL logging
# spring.jpa.show-sql: true

endpoints:
  TrainerServiceBaseUri: http://localhost:8083/trainer
