spring:
  application:
    name: LoginService
  data:
    rest:
      base-path: /api
      cors:
        allowed-origins: "http://localhost:3000" # Allow frontend to access the API
        allowed-methods: GET, POST, PUT, DELETE
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    # CONFIGURE THE BELOW FOR YOUR RESPECTIVE MYSQL DB
    url: jdbc:mysql://localhost:3306/coe692data_accounts
    username: awaislocal
    password: awaislocal
    driver-class-name: com.mysql.jdbc.Driver
    #  ------------------ >
server:
  port: 8082
