spring:
  application:
    name: LoginService
  data:
    rest:
      base-path: /api
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
# CONFIGURE THE BELOW FOR YOUR RESPECTIVE MYSQL DB < ----------
    url: jdbc:mysql://localhost:3306/coe692data_accounts
    username: awaislocal
    password: awaislocal
    driver-class-name: com.mysql.jdbc.Driver
#  ------------------ >
server:
  port: 8082

#spring.jpa.show-sql: true