version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
    # Remove the command override so that it doesn't try to use npm
    # command: npm run build  # This line should be removed
