spring:
  application:
    name: TrainerService
  data:
    rest:
      cors:
        allowed-origins: ${ALLOWED_CORS} # Or the specific origins you want to allow
        allowed-methods: GET, POST, PUT, DELETE, PATCH, OPTIONS
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  datasource:
    # Replace 'mysql' with the service name of your MySQL database in docker-compose.yml
    # Ensure the port matches the one exposed by your MySQL service
    url: ${DB_URL}
    username: awaislocal
    password: awaislocal
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8083
  # Uncomment the next line if you want the server to be accessible on all network interfaces
  # address: 0.0.0.0
# Uncomment the following line to enable SQL logging
# spring.jpa.show-sql: true
